### ISSUE TITLE
"Image not found" error on startup

### ISSUE THREAD

**Issue by carlosdagos** [mopidy/mopidy-spotify#134]
Hi,

I followed the steps using `brew` for installation, and when launching `mopidy` I get

```
ERROR    Extension spotify failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/__init__.py", line 49, in setup
    from mopidy_spotify.backend import SpotifyBackend
  File "/usr/local/lib/python2.7/site-packages/mopidy_spotify/backend.py", line 11, in <module>
    import spotify
  File "/usr/local/lib/python2.7/site-packages/spotify/__init__.py", line 81, in <module>
    from spotify._spotify import ffi, lib  # noqa
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/spotify/_spotify.so, 2): Library not loaded: @loader_path/../Frameworks/libspotify.framework/libspotify
  Referenced from: /usr/local/lib/python2.7/site-packages/spotify/_spotify.so
  Reason: image not found
```

I take it that `libspotify` is missing at `@loader_path/../Frameworks/libspotify.framework/libspotify`, but in my system it's installed at `/usr/local/opt/libspotify`. I'm not sure what `@loader_path` resolves to, because then I could create a symlink. Any help is appreciated.

**Comment by carlosdagos** [comment]
Fixed by running

```
sudo install_name_tool  -change "@loader_path/../Frameworks/libspotify.framework/libspotify" "/usr/local/opt/libspotify" /usr/local/lib/python2.7/site-packages/spotify/_spotify.so
```
