### ISSUE TITLE
Show_Media_Library timeout on ncmpcpp

### ISSUE THREAD

**Issue by frnkshin** [mopidy/mopidy-spotify#156]
```
ERROR    SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/core/library.py", line 142, in get_distinct
    values = future.get()
  File "/usr/lib/python2.7/site-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 200, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 294, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/library.py", line 26, in get_distinct
    field, query)
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/distinct.py", line 20, in get_distinct
    config, session, web_client, query)
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/distinct.py", line 45, in _get_distinct_artists
    for track in _get_playlist_tracks(config, session)
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/distinct.py", line 44, in <setcomp>
    artist.name
  File "/usr/lib/python2.7/site-packages/mopidy_spotify/distinct.py", line 119, in _get_playlist_tracks
    playlist.load(config['timeout'])
  File "/usr/lib/python2.7/site-packages/spotify/playlist.py", line 118, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s
```

```
$ mopidy deps
Executable: /usr/bin/mopidy
Platform: Linux-4.12.4-1-ARCH-x86_64-with-glibc2.2.5
Python: CPython 2.7.13 from /usr/lib/python2.7
Mopidy: 2.1.0 from /usr/lib/python2.7/site-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/site-packages
  requests>=2.0: 2.18.3 from /usr/lib/python2.7/site-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/site-packages
    idna<2.6,>=2.5: 2.5 from /usr/lib/python2.7/site-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/site-packages
  setuptools: 36.2.7 from /usr/lib/python2.7/site-packages
  tornado>=3.2: 4.5.1 from /usr/lib/python2.7/site-packages
    singledispatch: 3.4.0.3 from /usr/lib/python2.7/site-packages
      six: 1.10.0 from /usr/lib/python2.7/site-packages
    backports_abc>=0.4: 0.5 from /usr/lib/python2.7/site-packages
Mopidy-Spotify: 3.1.0 from /usr/lib/python2.7/site-packages
  Mopidy>=2.0: 2.1.0 from /usr/lib/python2.7/site-packages
    Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/site-packages
    requests>=2.0: 2.18.3 from /usr/lib/python2.7/site-packages
      chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/site-packages
      idna<2.6,>=2.5: 2.5 from /usr/lib/python2.7/site-packages
      urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/site-packages
    setuptools: 36.2.7 from /usr/lib/python2.7/site-packages
    tornado>=3.2: 4.5.1 from /usr/lib/python2.7/site-packages
      singledispatch: 3.4.0.3 from /usr/lib/python2.7/site-packages
        six: 1.10.0 from /usr/lib/python2.7/site-packages
      backports_abc>=0.4: 0.5 from /usr/lib/python2.7/site-packages
  Pykka>=1.1: 1.2.0 from /usr/lib/python2.7/site-packages
  pyspotify>=2.0.5: 2.0.5 from /usr/lib/python2.7/site-packages
    cffi>=1.0.0: 1.10.0 from /usr/lib/python2.7/site-packages
      pycparser: 2.18 from /usr/lib/python2.7/site-packages
  requests>=2.0: 2.18.3 from /usr/lib/python2.7/site-packages
    chardet<3.1.0,>=3.0.2: 3.0.4 from /usr/lib/python2.7/site-packages
    idna<2.6,>=2.5: 2.5 from /usr/lib/python2.7/site-packages
    urllib3<1.23,>=1.21.1: 1.22 from /usr/lib/python2.7/site-packages
  setuptools: 36.2.7 from /usr/lib/python2.7/site-packages
GStreamer: 1.12.2.0 from /usr/lib/python2.7/site-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.24.1
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad
```

I'm currently running `4.12.4-1-ARCH`

**Comment by ecly** [comment]
I get this as well - seems like it can't load the 'general library'. 
It does however work fine when you want to locate a song in the media library eg. using '\~' bind in ncmpcpp. It will then locate the artist and song in the media library.

My temporary fix to deal with this is just to reduce the timeout to something bearable, and only use media library through eg. '\~' and instead rely on searches.

In *.config/mopidy/mopidy.conf*
```
[spotify]
timeout = 2
```

**Comment by hshin23** [comment]
@ecly 
I just unbound the keymap to show_music_library to whatever the default keymap set to '1' is.

**Comment by ecly** [comment]
@hshin23 yeah, that's another workaround if you don't want to use the library altogether. I find it quite nice for browing songs by an artist of a song using '~'. I guess you can still use that feature without the musc library bind though, you'll just have to query the song every time. Either way, would be cool if the media library as a whole could be implemented in a way that doesn't cause hang when you visit it the first time without any context.

**Comment by colonelk1** [comment]
Same issue. Does anyone have suggestions how to get the local library up and running then?

**Comment by ecly** [comment]
@colonelk1 I think it's a matter of implementing it in mopidy-spotify, unless you use it indirectly,  by eg. going to a specific artist using '~' in ncmpcpp

**Comment by valerius21** [comment]
same error still exists for me too. It makes the general library useless.

**Comment by Risebell** [comment]
same here. the mentioned '~' workaround doesn't even work for me.

**Comment by marcosmoura** [comment]
Same here. ncmpcpp freezes.

**Comment by kingosticks** [comment]
This looks like it failed to load a playlist and will have been fixed by https://github.com/mopidy/mopidy-spotify/commit/f52babd10b1e187076e73f6cdbd2aaf56c7bbb60
