### ISSUE TITLE
Can't browse spotify

### ISSUE THREAD

**Issue by Pat71** [mopidy/mopidy-spotify#184]
Hi, I can't browse any Spotify lists, I always get a timeout:
```
INFO     Logged in to Spotify in online mode
ERROR    SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 19, in _backend_error_handling
    yield
  File "/usr/lib/python2.7/dist-packages/mopidy/core/library.py", line 112, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy_spotify/library.py", line 21, in browse
    return browse.browse(self._config, self._backend._session, uri)
  File "/usr/lib/python2.7/dist-packages/mopidy_spotify/browse.py", line 43, in browse
    return _browse_playlist(session, uri, config)
  File "/usr/lib/python2.7/dist-packages/mopidy_spotify/browse.py", line 66, in _browse_playlist
    sp_playlist.load(config['timeout'])
  File "/usr/lib/python2.7/dist-packages/spotify/playlist.py", line 118, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/spotify/utils.py", line 246, in load
    raise spotify.Timeout(timeout)
Timeout: Operation did not complete in 10.000s
```

**Comment by kingosticks** [comment]
Since you are loading a playlist here this is almost certainly related to https://github.com/mopidy/mopidy-spotify/issues/182. I think we can probably close this in favour of that issue.
