### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by brunomiguel** [mopidy/mopidy-spotify#198]
Hello.

I installed Mopidy and Mopidy-Spotify on Debian Stretch, using the Mopidy repo. When I launch Mopidy, after setting up my configuration file, I get this error:

```
ERROR    2018-09-19 04:44:21,174 [3588:MainThread] mopidy.__main__
  Extension spotify failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mopidy/__main__.py", line 121, in main
    extension.setup(registry)
  File "/usr/lib/python2.7/dist-packages/mopidy_spotify/__init__.py", line 52, in setup
    from mopidy_spotify.backend import SpotifyBackend
  File "/usr/lib/python2.7/dist-packages/mopidy_spotify/backend.py", line 11, in <module>
    import spotify
  File "/usr/local/lib/python2.7/dist-packages/spotify/__init__.py", line 1, in <module>
    from .client import Client
  File "/usr/local/lib/python2.7/dist-packages/spotify/client.py", line 13
    def __init__(self, auth: OAuth, requests_session=None):
                           ^
SyntaxError: invalid syntax
```
Opening and connecting any MPD client results in nothing.

I'm using Python Python 2.7.13, Mopidy 2.1.0 and Mopidy-Spotify 3.1.0

**Comment by brunomiguel** [comment]
You are correct. I've identified the culprit. Thanks! :+1: :)
