### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by cemzafer** [mopidy/mopidy-spotify#207]
Hi all, 
I have get the following error when someone access the mopidy and do search, any idea how to renew certificates?
Thanks.

``` python
ERROR    500 GET /iris/http/refresh_spotify_token (192.168.9.41) 502.21ms
ERROR    Uncaught exception GET /iris/http/refresh_spotify_token (192.168.9.41)
HTTPServerRequest(protocol='http', host='192.168.9.101:6680', method='GET', uri='/iris/http/refresh_spotify_token', version='HTTP/1.1', remote_ip='192.168.9.41', headers={'Accept-Language': 'en-us', 'Accept-Encoding': 'gzip, deflate', 'Host': '192.168.9.101:6680', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Safari/605.1.15', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://192.168.9.101:6680/iris/', 'Cookie': '_ga=GA1.1.1062285401.1537875547; _gat=1; _gid=GA1.1.1389605904.1545026374'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1425, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1627, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Iris-3.31.6-py2.7.egg/mopidy_iris/handlers.py", line 167, in get
    getattr(mem.iris, slug)(request=self, callback=lambda response, error=False: self.handle_result(id=id, method=slug, response=response, error=error))
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Iris-3.31.6-py2.7.egg/mopidy_iris/core.py", line 893, in refresh_spotify_token
    response = http_client.fetch(request)
  File "/usr/local/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch
    self._async_client.fetch, request, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 457, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by jodal** [comment]
While @kingosticks is right, I'd check that the clock on the Mopidy server is correct before reporting this to Mopidy-Iris. If the clock on the system is off with weeks/years, it would cause certificate validation to fail, as certificates are only valid for a few weeks to a couple of years.

**Comment by cemzafer** [comment]
@kingosticks, sorry to disturb the board, @jodal , You are absolutely right, I corrected the time sync and the problem gone fluently, it may be the reference to the others.
Thanks guys.
