### ISSUE TITLE
Fetching images for large playlist fails.

### ISSUE THREAD

**Issue by adamcik** [mopidy/mopidy-spotify#244]
Loading my 2000 track playlist in mopidy-mobile triggers the following error. I'll try and get some more debug details this evening. This was on master, not by modified code with playlist image support.

```
DEBUG    2019-12-19 10:12:56,975 [31128:HttpServer] mopidy.http.handlers
  Received WebSocket message from 127.0.0.1: '{"method":"core.library.get_images","params":{"uris":["spotify:track:5FpRRYLiHvFeiTFpY6lMep","spotify:track:5oImi7R1hqEPjVq6USKPHo","spotify:track:039XtTibKDPTELqQkWWnoE","spotify:track:6cAvZ8KGXYpwBfmYpBBGLC","spotify:track:7qRacgleydCoFZaZf8A1Ar","spotify:track:6LV40LkkTpDY3CV0AeJfax","spotify:track:3JMpKeWp4Iujt0knABM136","spotify:
track:3wQtzisWD2KTvgii3FjSJ0","spotify:track:7FnbXdQHeRp7IvZ1foTgfQ","spotify:track:0biIBivhgsbu0Hdy27LINa"]},"jsonrpc":"2.0","id":65}'
TRACE    2019-12-19 10:12:56,977 [31128:SpotifyBackend-6] mopidy_spotify.web
  Get 'tracks?ids=5FpRRYLiHvFeiTFpY6lMep%2C5oImi7R1hqEPjVq6USKPHo%2C039XtTibKDPTELqQkWWnoE%2C6cAvZ8KGXYpwBfmYpBBGLC%2C7qRacgleydCoFZaZf8A1Ar%2C6LV40LkkTpDY3CV0AeJfax%2C3JMpKeWp4Iujt0knABM136%2C3wQtzisWD2KTvgii3FjSJ0%2C7FnbXdQHeRp7IvZ1foTgfQ%2C0biIBivhgsbu0Hdy27LINa'
DEBUG    2019-12-19 10:12:57,005 [31128:SpotifyBackend-6] urllib3.connectionpool
  https://api.spotify.com:443 "GET /v1/tracks?ids=5FpRRYLiHvFeiTFpY6lMep%2C5oImi7R1hqEPjVq6USKPHo%2C039XtTibKDPTELqQkWWnoE%2C6cAvZ8KGXYpwBfmYpBBGLC%2C7qRacgleydCoFZaZf8A1Ar%2C6LV40LkkTpDY3CV0AeJfax%2C3JMpKeWp4Iujt0knABM136%2C3wQtzisWD2KTvgii3FjSJ0%2C7FnbXdQHeRp7IvZ1foTgfQ%2C0biIBivhgsbu0Hdy27LINa HTTP/1.1" 200 None
TRACE    2019-12-19 10:12:57,007 [31128:SpotifyBackend-6] mopidy_spotify.web
  New WebResponse URL: https://api.spotify.com/v1/tracks?ids=5FpRRYLiHvFeiTFpY6lMep%2C5oImi7R1hqEPjVq6USKPHo%2C039XtTibKDPTELqQkWWnoE%2C6cAvZ8KGXYpwBfmYpBBGLC%2C7qRacgleydCoFZaZf8A1Ar%2C6LV40LkkTpDY3CV0AeJfax%2C3JMpKeWp4Iujt0knABM136%2C3wQtzisWD2KTvgii3FjSJ0%2C7FnbXdQHeRp7IvZ1foTgfQ%2C0biIBivhgsbu0Hdy27LINa expires at: 2019-12-20 06:22:40.006936 [ETag: None]
INFO     2019-12-19 10:12:57,008 [31128:SpotifyBackend-6] pykka
  Exception returned from SpotifyBackend (urn:uuid:0ef59d6c-9aa8-419b-89bc-41cfe1550752) to caller:
Traceback (most recent call last):
  File "/home/adamcik/dev/mopidy-venv3/lib/python3.7/site-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/home/adamcik/dev/mopidy-venv3/lib/python3.7/site-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/home/adamcik/dev/mopidy-spotify/mopidy_spotify/library.py", line 35, in get_images
    return images.get_images(self._backend._web_client, uris)
  File "/home/adamcik/dev/mopidy-spotify/mopidy_spotify/images.py", line 36, in get_images
    result.update(_process_uris(web_client, uri_type, batch))
  File "/home/adamcik/dev/mopidy-spotify/mopidy_spotify/images.py", line 80, in _process_uris
    uri = ids_to_uris[item["id"]]
KeyError: '54WcX7oBwRRr8ngamUnQhV'
ERROR    2019-12-19 10:12:57,009 [31128:Core-9] mopidy.core.library
  SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/home/adamcik/dev/mopidy/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/home/adamcik/dev/mopidy/mopidy/core/library.py", line 181, in get_images
    if future.get() is None:
  File "/home/adamcik/dev/mopidy-venv3/lib/python3.7/site-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/home/adamcik/dev/mopidy-venv3/lib/python3.7/site-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/home/adamcik/dev/mopidy-venv3/lib/python3.7/site-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/home/adamcik/dev/mopidy-venv3/lib/python3.7/site-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/home/adamcik/dev/mopidy-spotify/mopidy_spotify/library.py", line 35, in get_images
    return images.get_images(self._backend._web_client, uris)
  File "/home/adamcik/dev/mopidy-spotify/mopidy_spotify/images.py", line 36, in get_images
    result.update(_process_uris(web_client, uri_type, batch))
  File "/home/adamcik/dev/mopidy-spotify/mopidy_spotify/images.py", line 80, in _process_uris
    uri = ids_to_uris[item["id"]]
KeyError: '54WcX7oBwRRr8ngamUnQhV'
```

**Comment by kingosticks** [comment]
This looks like #171. I don't think we have the same market but `3wQtzisWD2KTvgii3FjSJ0` seems to be relinked to.

**Comment by adamcik** [comment]
Sounds very plausible. Closing since it's dupe then.
