### ISSUE TITLE
Backend exception when browsing albums

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy-spotify#332]
When Spotify is disconnected and we try and browse albums we get this
```
INFO     2022-03-15 20:50:47,012 [1040:SpotifyEventLoop] mopidy_spotify.backend
  Disconnected from Spotify

20:50:48ERROR    2022-03-15 20:50:48,714 [1040:Core-9] mopidy.core.library
  SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 114, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3/dist-packages/mopidy_spotify/library.py", line 22, in browse
    uri=uri,
  File "/usr/lib/python3/dist-packages/mopidy_spotify/browse.py", line 61, in browse
    return _browse_album(session, uri, config)
  File "/usr/lib/python3/dist-packages/mopidy_spotify/browse.py", line 98, in _browse_album
    sp_album_browser.load(config["timeout"])
  File "/usr/lib/python3/dist-packages/spotify/album.py", line 273, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python3/dist-packages/spotify/utils.py", line 224, in load
    % session.connection.state
spotify.error.Error: Session must be logged in and online to load objects: <ConnectionState.DISCONNECTED: 2>

20:50:49ERROR    2022-03-15 20:50:49,957 [1040:Core-9] mopidy.core.library
  SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 114, in _browse
    result = backend.library.browse(uri).get()
  File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3/dist-packages/mopidy_spotify/library.py", line 22, in browse
    uri=uri,
  File "/usr/lib/python3/dist-packages/mopidy_spotify/browse.py", line 61, in browse
    return _browse_album(session, uri, config)
  File "/usr/lib/python3/dist-packages/mopidy_spotify/browse.py", line 98, in _browse_album
    sp_album_browser.load(config["timeout"])
  File "/usr/lib/python3/dist-packages/spotify/album.py", line 273, in load
    return utils.load(self._session, self, timeout=timeout)
  File "/usr/lib/python3/dist-packages/spotify/utils.py", line 224, in load
    % session.connection.state
spotify.error.Error: Session must be logged in and online to load objects: <ConnectionState.DISCONNECTED: 2>
```

We need to catch exceptions in `_browse_album` and any similar places. 

First reported at https://discourse.mopidy.com/t/disconnected-from-spotify/5370/4

**Comment by gaunap** [comment]
Is there any workaround I can apply in my application code to avoid this exception to happen?
It currently happens quite often in my application...

**Comment by gaunap** [comment]
Really great that this issue has been fixed. Can you tell when it will be released?
