### ISSUE TITLE
Unknown config key

### ISSUE THREAD

**Issue by scourii** [mopidy/mopidy-spotify#336]
I've been trying to connect to Spotify with mopidy, but everytime I start it up, I always get an error that says `spotify/client_id unknown config key.` and `spotify/client_secret unknown config key.` I've tried to refresh both and I've updated my mopidy.conf file in my .config directory, however it still doesn't seem to work. What can I do to fix this? I've replicated the demo configuration file and I'm pretty sure everything else works fine.

**Comment by kingosticks** [comment]
Sorry, are you still hitting this?

**Comment by scourii** [comment]
Hi, I missed this message too! I haven't tried to use it since, but I will attempt again today and I'll update you!

**Comment by scourii** [comment]
Hi, I just retested this. I still get errors:
```WARNING  2023-02-06 20:53:19,581 [7277:MainThread] mopidy.__main__
  Found spotify configuration errors. The extension has been automatically disabled:
WARNING  2023-02-06 20:53:19,581 [7277:MainThread] mopidy.__main__
    spotify/client_id unknown config key.
WARNING  2023-02-06 20:53:19,581 [7277:MainThread] mopidy.__main__
    spotify/client_secret unknown config key.
WARNING  2023-02-06 20:53:19,581 [7277:MainThread] mopidy.__main__
  Please fix the extension configuration errors or disable the extensions to silence these messages.
```
Unsure what's up, I used the https://mopidy.com/ext/spotify/ website to obtain my client_id and secret, but it doesn't work. Everything else seems fine though, I get no other warnings.

**Comment by scourii** [comment]
Testing on ncmpcpp, I can see that Spotify shows up in the user interface, however I get an error like this:
```
ERROR    2023-02-06 20:56:44,210 [8301:Core-7] mopidy.core.library
  SpotifyTunigoBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.tunigo.com', port=443): Max retries exceeded with url: /v3/space/toplists?locale=en&product=premium&version=6.38.31&platform=web&per_page=1000 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7faad83d0ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

```

**Comment by kingosticks** [comment]
SpotifyTunigo is not supported. It's really old and doesn't work on Mopidy 3. Uninstall it.

**Comment by kingosticks** [comment]
Neither of my precious 2 messages above actually explain why you are hitting this error. You could do `mopidy deps` and `mopidy config` and see a bit more.

**Comment by kingosticks** [comment]
Re-open if this is a problem in the latest version (unreleased as of now).
