### ISSUE TITLE
Bug: 'cffi' package version mismatch; unable to install on Kubuntu 22.04.1 LTS 

### ISSUE THREAD

**Issue by NeilPandya** [mopidy/mopidy-spotify#348]
Hello and thanks for your hard work on this software!

I recently installed mopidy, and was trying to get mopidy-spotify working, but was hit with the following exception when trying to install, as per the [instructions](https://mopidy.com/ext/spotify/):

```
neil@Zephyrus:~$ sudo python3 -m pip install Mopidy-Spotify
Collecting Mopidy-Spotify
  Using cached Mopidy_Spotify-4.1.1-py3-none-any.whl (31 kB)
Requirement already satisfied: Pykka>=2.0.1 in /usr/lib/python3/dist-packages (from Mopidy-Spotify) (2.0.3)
Requirement already satisfied: requests>=2.20.0 in /usr/lib/python3/dist-packages (from Mopidy-Spotify) (2.25.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from Mopidy-Spotify) (59.6.0)
Requirement already satisfied: Mopidy>=3.0.0 in /usr/lib/python3/dist-packages (from Mopidy-Spotify) (3.2.0)
Collecting pyspotify>=2.0.5
  Using cached pyspotify-2.1.4.tar.gz (157 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 174, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 3, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 109, in setup
          _setup_distribution = dist = klass(attrs)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 459, in __init__
          _Distribution.__init__(
        File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 837, in finalize_options
          ep(self)
        File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 858, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-31he8_4p/normal/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-31he8_4p/normal/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-31he8_4p/normal/local/lib/python3.10/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "spotify/_spotify_build.py", line 18, in <module>
          ffi = cffi.FFI()
        File "/tmp/pip-build-env-31he8_4p/normal/local/lib/python3.10/dist-packages/cffi/api.py", line 54, in __init__
          raise Exception("Version mismatch: this is the 'cffi' package version %s, located in %r.  When we import the top-level '_cffi_backend' extension module, we get version %s, located in %r.  The two versions should be equal; check your installation." % (
      Exception: Version mismatch: this is the 'cffi' package version 1.15.1, located in '/tmp/pip-build-env-31he8_4p/normal/local/lib/python3.10/dist-packages/cffi/api.py'.  When we import the top-level '_cffi_backend' extension module, we get version 1.15.0, located in '/usr/lib/python3/dist-packages/_cffi_backend.cpython-310-x86_64-linux-gnu.so'.  The two versions should be equal; check your installation.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

I _have already installed_ ```cffi==1.15.1``` package via the following command: ```sudo python3 pip -m install cffi==1.15.1```.

Here is the full package list of my python environment (```sudo pip3 list```):

```
Package                 Version
----------------------- ---------------
anyio                   3.5.0
apt-xapian-index        0.49
attrs                   21.2.0
Babel                   2.8.0
beautifulsoup4          4.10.0
black                   21.10b0
blinker                 1.4
certifi                 2020.6.20
cffi                    1.15.1
chardet                 4.0.0
charset-normalizer      2.0.6
click                   8.0.3
colorama                0.4.4
command-not-found       0.3
commonmark              0.9.1
cov-core                1.15.0
coverage                6.2
cryptography            3.4.8
cupshelpers             1.0
dbus-python             1.2.18
distro                  1.7.0
distro-info             1.1build1
execnet                 1.9.0
flake8                  4.0.1
fuse-python             1.0.2
gpg                     1.16.0-unknown
h11                     0.13.0
html5lib                1.1
httpcore                0.14.5
httplib2                0.20.2
httpx                   0.22.0
idna                    3.3
importlib-metadata      4.6.4
iniconfig               1.1.1
isort                   5.6.4
jeepney                 0.7.1
Jinja2                  3.0.3
keyring                 23.5.0
language-selector       0.1
launchpadlib            1.10.16
lazr.restfulclient      0.14.4
lazr.uri                1.0.6
livereload              2.6.3
lxml                    4.8.0
Markdown                3.3.6
MarkupSafe              2.0.1
mccabe                  0.6.1
mkdocs                  1.1.2
Mopidy                  3.2.0
more-itertools          8.10.0
mypy                    0.942
mypy-extensions         0.4.3
nala                    0.11.1
netifaces               0.11.0
nose2                   0.9.2
oauthlib                3.2.0
olefile                 0.46
packaging               21.3
pathspec                0.9.0
pexpect                 4.8.0
Pillow                  9.0.1
pip                     22.0.2
platformdirs            2.5.1
pluggy                  0.13.0
psutil                  5.9.0
ptyprocess              0.7.0
py                      1.10.0
pycairo                 1.20.1
pycodestyle             2.8.0
pycparser               2.21
pycups                  2.0.1
pyflakes                2.4.0
Pygments                2.11.2
PyGObject               3.42.1
pyinotify               0.9.6
PyJWT                   2.3.0
Pykka                   2.0.3
pylibacl                0.6.0
pyparsing               2.4.7
PyQt5                   5.15.6
PyQt5-sip               12.9.1
pytest                  6.2.5
pytest-cov              3.0.0
pytest-forked           1.4.0
pytest-sugar            0.9.4
pytest-xdist            2.5.0
python-apt              2.3.0+ubuntu2.1
python-debian           0.1.43ubuntu1
pytz                    2022.1
pyxattr                 0.7.2
PyYAML                  5.4.1
reportlab               3.6.8
requests                2.25.1
rfc3986                 1.5.0
rich                    11.2.0
screen-resolution-extra 0.0.0
SecretStorage           3.3.1
setuptools              59.6.0
shellingham             1.4.0
six                     1.16.0
sniffio                 1.2.0
socksio                 1.0.0
soupsieve               2.3.1
ssh-import-id           5.11
systemd-python          234
termcolor               1.1.0
toml                    0.10.2
tomli                   1.2.2
tornado                 6.1
typed-ast               1.4.3
typer                   0.4.0
typing-extensions       3.10.0.2
ubuntu-advantage-tools  27.11.3
ubuntu-drivers-common   0.0.0
ufw                     0.36.1
unattended-upgrades     0.1
urllib3                 1.26.5
usb-creator             0.3.7
wadllib                 1.3.6
webencodings            0.5.1
wheel                   0.37.1
xkit                    0.0.0
zipp                    1.0.0
```

Is there an open or closed issue that deals with this bug that I can be pointed towards to troubleshoot this?

Thanks in advance,

Neil

```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-53-generic (64-bit)
Graphics Platform: X11
Processors: 16 × AMD Ryzen 9 5900HS with Radeon Graphics
Memory: 22.9 GiB of RAM
Graphics Processor: AMD RENOIR; NVIDIA GeForce RTX 3080 Laptop
```

**Comment by NeilPandya** [comment]
Sorry, didn't realize that:

1. One needs a Spotify Premium account.
2. This repo is not being maintained.
3. Spotify has deprecated ```libspotify```; features are now limited or broken.

Hence, I will close this issue as "stale".

**Comment by kingosticks** [comment]
1 and 3 are true. 2 is false (although it is true for pyspotify, which is maybe what you meant).

The easiest (and recommended) way to install on Debian/Ubuntu is via APT, rather that PyPI. I think APT would have avoided the issue although installing pyspotify from source should be supported. Either way, if there's a bug it is in pyspotify.

**Comment by kingosticks** [comment]
For anyone else (that does have a Premium account and *needs* to install from source), I would expect `sudo python3 -m pip install --upgrade cffi==1.15.0` would also solve the problem. You seem to need your pip installed version to match your system version. Not sure why this is suddenly a problem though, surely these versions of cffi are often out of sync.

**Comment by NeilPandya** [comment]
> The easiest (and recommended) way to install on Debian/Ubuntu is via APT, rather that PyPI. I think APT would have avoided the issue although installing pyspotify from source should be supported. Either way, if there's a bug it is in pyspotify.

@kingosticks, my wife is letting me authenticate with her premium account now. Coincidentally, I tried installing via ```apt``` initially; however, the package seems to have been removed:

```
neil@Zephyrus:~$ sudo apt install mopidy-spotify
[sudo] password for neil: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package mopidy-spotify
```

Perhaps I needed to add the archive's GPG key and the APT repo first, if I'm thinking about the problem correctly?

```
sudo mkdir -p /usr/local/share/keyrings
sudo wget -q -O /usr/local/share/keyrings/mopidy-archive-keyring.gpg \
  https://apt.mopidy.com/mopidy.gpg
```
```
sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list
```
```
sudo apt update
sudo apt install mopidy && sudo apt install mopidy-spotify
```

Would this work, do you think?

**Comment by kingosticks** [comment]
Yes, you need to add our APT repo first and then that should work.

**Comment by kingosticks** [comment]
However, point 3 is still very true and **currently Mopidy-Spotify is effectively unusable**. Some people are using a work-in-progress version that restores playback support but it's a collection of hacks and a lot of work and I don't advise going down that road. I desperately need to get back to working on this.

> Playback/streaming does not work for any version of mopidy-spotify

**Comment by kingosticks** [comment]
I'm not sure if we need this open issue. Do we?

**Comment by NeilPandya** [comment]
> I'm not sure if we need this open issue. Do we?

Forgive, will mark as closed, as you've answered the questions posed.
