### ISSUE TITLE
Browsing in Spotify Library doesn't work

### ISSUE THREAD

**Issue by Benni08** [mopidy/mopidy-spotify#364]
Hey, 

im getting an error when browsing Spotify via Iris Webbrowser:

INFO     2023-10-19 13:01:03,083 [9405:SpotifyBackend-6 (_actor_loop)] mopidy_spotify.lookup
  Failed to lookup 'spotify:directory': Could not parse 'spotify:directory' as a Spotify URI
ERROR    2023-10-19 13:01:03,116 [9405:Core-8 (_actor_loop)] mopidy.core.library
  SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.11/dist-packages/mopidy/core/library.py", line 194, in get_images
    if future.get() is None:
       ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pykka/_threading.py", line 68, in get
    raise exc_value
  File "/usr/local/lib/python3.11/dist-packages/pykka/_actor.py", line 238, in _actor_loop_running
    response = self._handle_receive(envelope.message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pykka/_actor.py", line 349, in _handle_receive
    return callee(*message.args, **message.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mopidy_spotify/library.py", line 35, in get_images
    return images.get_images(self._backend._web_client, uris)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mopidy_spotify/images.py", line 18, in get_images
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mopidy_spotify/images.py", line 18, in <genexpr>
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
                   ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mopidy_spotify/images.py", line 40, in _parse_uri
    uri_type, uri_id = parsed_uri.path.split(":")[:2]
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)
ERROR    2023-10-19 13:01:03,135 [9405:Core-8 (_actor_loop)] mopidy.core.library
  SpotifyBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.11/dist-packages/mopidy/core/library.py", line 194, in get_images
    if future.get() is None:
       ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pykka/_threading.py", line 68, in get
    raise exc_value
  File "/usr/local/lib/python3.11/dist-packages/pykka/_actor.py", line 238, in _actor_loop_running
    response = self._handle_receive(envelope.message)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pykka/_actor.py", line 349, in _handle_receive
    return callee(*message.args, **message.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mopidy_spotify/library.py", line 35, in get_images
    return images.get_images(self._backend._web_client, uris)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mopidy_spotify/images.py", line 18, in get_images
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mopidy_spotify/images.py", line 18, in <genexpr>
    uris = sorted((_parse_uri(u) for u in uris), key=uri_type_getter)
                   ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/mopidy_spotify/images.py", line 40, in _parse_uri
    uri_type, uri_id = parsed_uri.path.split(":")[:2]
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

the requested URI is:
spotify:directory

**Comment by kingosticks** [comment]
Thanks. We need to handle this exception gracefully and return an empty result when a client tries to get an image for a directory (arguably a weird thing to try and do, I have previously tried to deter Iris from doing this).

**Comment by kingosticks** [comment]
Note, browsing will work in other clients. This is Iris specific.

**Comment by Benni08** [comment]
ive already tried mopify, there the spotify browsing also not working.

can you tell me a working client?

Best Regards 
Ben

**Comment by kingosticks** [comment]
Mopify hasn't been maintained for a long time. Not sure how working that is. There's a list of webclients at https://mopidy.com/ext/

Mopidy Musicbox Webclient should be fine, or any MPD client.
