### ISSUE TITLE
private_session causes error 'private_session can only be set when the session is logged '

### ISSUE THREAD

**Issue by richardambridge** [mopidy/mopidy-spotify#38]
With the latest version from develop I get the following error:

``` python
INFO     Loaded 0 local tracks using json
ERROR    Unhandled exception in SpotifyBackend (urn:uuid:e96f43c1-949a-46cd-ba53-c61273b235ad):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 191, in _actor_loop
    self.on_start()
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Spotify-2.0.0-py2.7.egg/mopidy_spotify/backend.py", line 52, in on_start
    self._session = self._get_session(self._config)
  File "/usr/local/lib/python2.7/dist-packages/Mopidy_Spotify-2.0.0-py2.7.egg/mopidy_spotify/backend.py", line 77, in _get_session
    config['spotify']['private_session'])
  File "/usr/local/lib/python2.7/dist-packages/pyspotify-2.0.0b4-py2.7-linux-x86_64.egg/spotify/social.py", line 41, in private_session
    'private_session can only be set when the session is logged '
RuntimeError: private_session can only be set when the session is logged in. This is temporary workaround of a libspotify bug, causing the application to segfault otherwise.
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
ERROR    Uncaught exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Mopidy-0.19.5-py2.7.egg/mopidy/commands.py", line 282, in run
    core = self.start_core(mixer, backends)
  File "/usr/local/lib/python2.7/dist-packages/Mopidy-0.19.5-py2.7.egg/mopidy/commands.py", line 365, in start_core
    return Core.start(mixer=mixer, backends=backends).proxy()
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 93, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Mopidy-0.19.5-py2.7.egg/mopidy/core/actor.py", line 46, in __init__
    self.backends = Backends(backends)
  File "/usr/local/lib/python2.7/dist-packages/Mopidy-0.19.5-py2.7.egg/mopidy/core/actor.py", line 119, in __init__
    has_library = b.has_library().get()
  File "/usr/lib/python2.7/dist-packages/pykka/future.py", line 299, in get
    exec('raise exc_info[0], exc_info[1], exc_info[2]')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 470, in ask
    self.tell(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 437, in tell
    raise _ActorDeadError('%s not found' % self)
ActorDeadError: SpotifyBackend (urn:uuid:e96f43c1-949a-46cd-ba53-c61273b235ad) not found
INFO     Stopping Mopidy frontends
INFO     Stopping Mopidy core
INFO     Stopping Mopidy backends
INFO     Stopping Mopidy audio
INFO     Stopping Mopidy mixer
```

I have `private_session = False` in config.

**Comment by richardambridge** [comment]
Created pull request #39
