### ISSUE TITLE
Max recursion depth reached and segfault if searching right after startup

### ISSUE THREAD

**Issue by jodal** [mopidy/mopidy-spotify#49]
To reproduce:

1. Start Mopidy develop with Mopidy-Spotify develop
2. Make a search as soon as possible

Variations:

- I've managed to reproduce this several times. The crash is not in the search code path, as I sometime get the search result before the crash happens.
- If I wait a few seconds extra after startup before doing the search, nothing crashes.

Crash output:

```
DEBUG    2015-03-24 16:39:59,771 [30542:SpotifyEventLoop] spotify.playlist
  Playlist update in progress
DEBUG    2015-03-24 16:39:59,771 [30542:SpotifyEventLoop] spotify.session
  libspotify log message: 15:39:59.771 W [playlist.cpp:45] Adding observer while updating
DEBUG    2015-03-24 16:39:59,772 [30542:SpotifyEventLoop] spotify.playlist
  Playlist update in progress
DEBUG    2015-03-24 16:39:59,772 [30542:SpotifyEventLoop] spotify.session
  libspotify log message: 15:39:59.772 W [playlist.cpp:45] Adding observer while updating
DEBUG    2015-03-24 16:39:59,772 [30542:SpotifyEventLoop] spotify.playlist
  Playlist update in progress
DEBUG    2015-03-24 16:39:59,773 [30542:SpotifyEventLoop] spotify.session
  libspotify log message: 15:39:59.773 W [playlist.cpp:45] Adding observer while updating
DEBUG    2015-03-24 16:39:59,773 [30542:SpotifyEventLoop] spotify.playlist
  Playlist update in progress
DEBUG    2015-03-24 16:39:59,773 [30542:SpotifyEventLoop] spotify.session
  libspotify log message: 15:39:59.773 W [playlist.cpp:45] Adding observer while updating
DEBUG    2015-03-24 16:39:59,774 [30542:SpotifyEventLoop] spotify.playlist
  Playlist update in progress
From callback <function log_message at 0x7f67769f68c0>:
Traceback (most recent call last):
  File "/home/jodal/dev/pyspotify2/spotify/session.py", line 1010, in log_message
    logger.debug('libspotify log message: %s', data)
  File "/usr/lib/python2.7/logging/__init__.py", line 1148, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1252, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 269, in __init__
    if (args and len(args) == 1 and isinstance(args[0], collections.Mapping)
RuntimeError: maximum recursion depth exceeded
Traceback (most recent call last):
  File "/home/jodal/dev/mopidy/mopidy/utils/log.py", line 166, in emit
From callback <function playlist_update_in_progress at 0x7f67769b1230>:
Traceback (most recent call last):
  File "/home/jodal/dev/pyspotify2/spotify/playlist.py", line 643, in playlist_update_in_progress
    logger.debug('Playlist update in progress')
  File "/usr/lib/python2.7/logging/__init__.py", line 1148, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1279, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1289, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1329, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 757, in handle
    self.emit(record)
  File "/home/jodal/dev/mopidy/mopidy/utils/log.py", line 171, in emit
    self.handleError(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 810, in handleError
    None, sys.stderr)
  File "/usr/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/home/jodal/dev/virtualenvs/mopidy/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
RuntimeError: maximum recursion depth exceeded
From callback <function log_message at 0x7f67769f68c0>:
Traceback (most recent call last):
  File "/home/jodal/dev/pyspotify2/spotify/session.py", line 1010, in log_message
    logger.debug('libspotify log message: %s', data)
  File "/usr/lib/python2.7/logging/__init__.py", line 1148, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1252, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 269, in __init__
    if (args and len(args) == 1 and isinstance(args[0], collections.Mapping)
  File "/home/jodal/dev/virtualenvs/mopidy/lib/python2.7/abc.py", line 132, in __instancecheck__
    if subclass is not None and subclass in cls._abc_cache:
  File "/home/jodal/dev/virtualenvs/mopidy/lib/python2.7/_weakrefset.py", line 72, in __contains__
    wr = ref(item)
RuntimeError: maximum recursion depth exceeded
DEBUG    2015-03-24 16:39:59,779 [30542:SpotifyEventLoop] spotify.playlist
  Playlist update in progress
From callback <function log_message at 0x7f67769f68c0>:
Traceback (most recent call last):
  File "/home/jodal/dev/pyspotify2/spotify/session.py", line 1010, in log_message
    logger.debug('libspotify log message: %s', data)
  File "/usr/lib/python2.7/logging/__init__.py", line 1148, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1252, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
RuntimeError: maximum recursion depth exceeded while calling a Python object
From callback <function playlist_update_in_progress at 0x7f67769b1230>:
Traceback (most recent call last):
  File "/home/jodal/dev/pyspotify2/spotify/playlist.py", line 643, in playlist_update_in_progress
    logger.debug('Playlist update in progress')
  File "/usr/lib/python2.7/logging/__init__.py", line 1148, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1252, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
RuntimeError: maximum recursion depth exceeded while calling a Python object
From callback <function log_message at 0x7f67769f68c0>:
Traceback (most recent call last):
  File "/home/jodal/dev/pyspotify2/spotify/session.py", line 1010, in log_message
    logger.debug('libspotify log message: %s', data)
  File "/usr/lib/python2.7/logging/__init__.py", line 1148, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1252, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 269, in __init__
    if (args and len(args) == 1 and isinstance(args[0], collections.Mapping)
RuntimeError: maximum recursion depth exceeded while calling a Python object
From callback <function playlist_update_in_progress at 0x7f67769b1230>:
Traceback (most recent call last):
  File "/home/jodal/dev/pyspotify2/spotify/playlist.py", line 643, in playlist_update_in_progress
    logger.debug('Playlist update in progress')
  File "/usr/lib/python2.7/logging/__init__.py", line 1148, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1252, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 273, in __init__
    self.levelname = getLevelName(level)
  File "/usr/lib/python2.7/logging/__init__.py", line 168, in getLevelName
    return _levelNames.get(level, ("Level %s" % level))
RuntimeError: maximum recursion depth exceeded while getting the str of an object
[1]    30542 segmentation fault (core dumped)  mopidy -o soundcloud/enabled=false -o youtube/enabled=false -o  -o
```

Full debug log: https://gist.github.com/jodal/e1a3d64d9d34eaafa2e8

**Comment by kingosticks** [comment]
I also see this when I restart Mopidy after performing a search; musicbox-weblcient will automatically try to re-perform the search soon as Mopidy comes back up, at which points it crashes with the same error.
http://dpaste.com/3V20QXS

**Comment by 9and3r** [comment]
I am getting a similar error with <a href="https://github.com/9and3r/mopidy-touchscreen">Mopidy-Touchscreen</a>
If I comment <a href="https://github.com/9and3r/mopidy-touchscreen/blob/develop/mopidy_touchscreen/screens/playlist_screen.py#L15">this line</a> the error disappears. So it also happens with core.playlists.playlists.get().

Crash output:

```
From cffi callback <function playlist_update_in_progress at 0x7f607da27050>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 645, in playlist_update_in_progress
    spotify._session_instance, sp_playlist, add_ref=True)
  File "/usr/local/lib/python2.7/dist-packages/spotify/__init__.py", line 60, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 46, in _cached
    playlist = Playlist(session, sp_playlist=sp_playlist, add_ref=add_ref)
  File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 67, in __init__
    lib.sp_playlist_add_ref(sp_playlist)
  File "/usr/local/lib/python2.7/dist-packages/spotify/__init__.py", line 59, in wrapper
    with _lock:
  File "/usr/lib/python2.7/threading.py", line 171, in acquire
    self._note("%s.acquire(%s): recursive success", self, blocking)
RuntimeError: maximum recursion depth exceeded
From cffi callback <function log_message at 0x7f607cc4a6e0>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spotify/session.py", line 1010, in log_message
    logger.debug('libspotify log message: %s', data)
  File "/usr/lib/python2.7/logging/__init__.py", line 1140, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
RuntimeError: maximum recursion depth exceeded while calling a Python object
From cffi callback <function playlist_update_in_progress at 0x7f607da27050>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 643, in playlist_update_in_progress
    logger.debug('Playlist update in progress')
  File "/usr/lib/python2.7/logging/__init__.py", line 1140, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
RuntimeError: maximum recursion depth exceeded while calling a Python object
From cffi callback <function log_message at 0x7f607cc4a6e0>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spotify/session.py", line 1010, in log_message
    logger.debug('libspotify log message: %s', data)
  File "/usr/lib/python2.7/logging/__init__.py", line 1140, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 263, in __init__
    if args and len(args) == 1 and isinstance(args[0], dict) and args[0]:
RuntimeError: maximum recursion depth exceeded while calling a Python object
From cffi callback <function playlist_update_in_progress at 0x7f607da27050>:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/spotify/playlist.py", line 643, in playlist_update_in_progress
    logger.debug('Playlist update in progress')
  File "/usr/lib/python2.7/logging/__init__.py", line 1140, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1270, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/logging/__init__.py", line 1244, in makeRecord
    rv = LogRecord(name, level, fn, lno, msg, args, exc_info, func)
  File "/usr/lib/python2.7/logging/__init__.py", line 266, in __init__
    self.levelname = getLevelName(level)
  File "/usr/lib/python2.7/logging/__init__.py", line 167, in getLevelName
    return _levelNames.get(level, ("Level %s" % level))
RuntimeError: maximum recursion depth exceeded while getting the str of an object
Fatal Python error: (pygame parachute) Segmentation Fault
Aborted (core dumped)

```

**Comment by jodal** [comment]
Closing, as this is tracked in mopidy/pyspotify#153.
