### ISSUE TITLE
starting a song after idle breaks system sound

### ISSUE THREAD

**Issue by alp-nGlow** [mopidy/mopidy-spotify#83]
##  This very well could be a config issue on my end, but i'm using default configs.  If this is my problem and this is the wrong place for this, I apologize, please direct me to the nearest relevant forum. 

After starting mopidy, then ncmpcpp, i could search spotify and listen to music, after sitting idle for a few minutes, i search a song and play it, but there is no sound.  system levels are turned up, but no applications produce sound.  the mopidy window gave me this, which i hope may bring me closer to the heart of the problem and closer to a solution.

``` python
ERROR    Unhandled exception in MpdSession (urn:uuid:d4cc0913-16af-404a-8d5e-96a71f41566e):
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 304, in _handle_receive
    return self.on_receive(message)
  File "/usr/lib/python2.7/dist-packages/mopidy/internal/network.py", line 370, in on_receive
    self.on_line_received(line)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/session.py", line 34, in on_line_received
    response = self.dispatcher.handle_request(line)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 47, in handle_request
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 68, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 76, in _catch_mpd_ack_errors_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 68, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 86, in _authenticate_filter
    return self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 68, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 105, in _command_list_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 68, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 134, in _idle_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 68, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 147, in _add_ok_filter
    response = self._call_next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 68, in _call_next_filter
    return next_filter(request, response, filter_chain)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 159, in _call_handler_filter
    response = self._format_response(self._call_handler(request))
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/dispatcher.py", line 174, in _call_handler
    return protocol.commands.call(tokens, context=self.context)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/protocol/__init__.py", line 180, in call
    return self.handlers[tokens[0]](context, *tokens[1:])
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/protocol/__init__.py", line 158, in validate
    return func(**callargs)
  File "/usr/lib/python2.7/dist-packages/mopidy/mpd/protocol/current_playlist.py", line 73, in addid
    uris=[uri], at_position=songpos).get()
  File "/usr/lib/python2.7/dist-packages/pykka/threading.py", line 52, in get
    compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python2.7/dist-packages/pykka/compat.py", line 12, in reraise
    exec('raise tp, value, tb')
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 201, in _actor_loop
    response = self._handle_receive(message)
  File "/usr/lib/python2.7/dist-packages/pykka/actor.py", line 295, in _handle_receive
    return callee(*message['args'], **message['kwargs'])
  File "/usr/lib/python2.7/dist-packages/mopidy/core/tracklist.py", line 440, in add
    'Tracklist may contain at most %d tracks.' % max_length)
TracklistFull: (u'Tracklist may contain at most 10000 tracks.', None)
```

**Comment by jodal** [comment]
It sounds like you haven't queued a single track, but a collection of more than 10000 tracks. Note that some results in the Mopidy-Spotify search results are on the form "Artist: Foo" which will queue all tracks by that artist instead of a single track.

The silence you experienced was probably Mopidy being busy adding the 10000 tracks to the tracklist before it hit its limit of 10000 tracks (for compatibility with MPD clients).

**Comment by alp-nGlow** [comment]
Would that persist after killing the process, or reboot?

**Comment by jodal** [comment]
No, the tracklist is not persisted.

**Comment by alp-nGlow** [comment]
sorry for the trouble, I'm just getting into sound in linux, and i didn't realize that "MM" below a channel in alsamixer meant that it was muted.   I thought for sure that I had un-muted all channels.  So, I've learned an important lesson today.  But one more question, is there a reason that my master volume would have been muted when this happened?  I just don't see a reason for that.

**Comment by jodal** [comment]
No, I cant't immediately think of any reason why it was muted.
